version: '3.3'
services:
  warehouseapp:
    image: jetti443/javajettapp5.0
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: warehouseapp
      RDS_USERNAME: todos-user
      RDS_PASSWORD: dummytodos

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword 
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: dummytodos
      MYSQL_DATABASE: warehouseapp